# Site settings
url: http://localhost:4000

# Blog settings
markdown: kramdown
highlighter: rouge
# permalink: pretty
permalink: /:title/
paginate: 7
paginate_path: "/blog/page:num/"

# Build settings
plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap, jekyll-seo-tag]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "legacy"]

sass:
  sass_dir: assets/scss
  style: compressed